(defpackage slashcord
  (:use :cl)
  (:local-nicknames (:a alexandria)
                    (:d lispcord)
                    (:i :ironclad)
                    (:f flexi-streams)
                    (:s serapeum)
                    (:h :hunchentoot)
                    (:jzon :com.inuoe.jzon))
  (:import-from :serapeum :-> :dict)
  (:import-from :easy-routes :defroute)
  (:export :interaction :interaction-type))
